### PR TITLE
(AIR-143) : [IMP] Turn Notifier class into a singleton

### PR DESCRIPTION
**Pull request by smurf-U**
https://github.com/airbrake/pybrake/issues/168

### CODE REVIEW

**Comment by kyrylo** [comment]
In #168 it is mentioned that the user has to create two instance of Notifier and this is bad because of spawning two thread pools. I don't see how it's bad, though. Could you elaborate, please?

**Comment by smurf-U** [comment]
If an application starts numerous instances of the notifier, it will send error notifications or metric stats to Airbrake asynchronously many times.

**Comment by kyrylo** [comment]
> If an application starts numerous instances of the notifier

Why is that necessarily a bad thing? The singleton design won't let anyone else in the app send their data to any other Airbrake project. From what I understand, after this change there won't be a way to send errors/metrics to any other project at the same time (and there's no workaround). That's a downside.

**Comment by smurf-U** [comment]
> Why is that necessarily a bad thing?

when two instances with the same `project_id` and `project_key` are generated. As a result, the identical statistics or notifications will be sent twice.

So, do we need to limit instance creation to those with the same `project_id` and `project_key`? So, what do you suggest?

**Comment by kyrylo** [comment]
I think we shouldn't do anything here, to be honest. If the generation generates two instances of the same notifier, it's not Airbrake's problem. It's the problem of the app configuration. https://github.com/airbrake/pybrake/issues/168 specifically mentions the problem of spawning two thread pools, but that's not a real issue. I don't have a good understanding of the configuration details in #168 but I am pretty sure singletons is not what we want. None of our notifiers are singletons.

**Comment by smurf-U** [comment]
Got it. I'll talk to Scott about it and then close the issue once I've explained everything on it. For the time being, I'm closing this PR.

**Pull request closed without merging**
