### PR TITLE
Disabled arguments warning

### PR DESCRIPTION
**Pull request by salonijain0918**
Disable the too-many-arguments warnings for pylint checks.

### CODE REVIEW

**Comment by kyrylo** [comment]
Disabling will fix the build but why not to fix them?

**Comment by salonijain0918** [comment]
In real, there are multiple instances of these programming errors and coding standard issues in each single file that are even not being reported here. I fixed a few basic ones but the circular dependency checks are creating problems which may take longer time to fix and I anyway has another task for code cleanup after the sample applications, so disabled for now.

**Comment by salonijain0918** [comment]
@kyrylo I will push the few fixes that are fine and keep the dependencies one disabled for now till I start working on code clean up ticket?

**Comment by kyrylo** [comment]
> In real, there are multiple instances of these programming errors and coding standard issues in each single file that are even not being reported here.

Probably it's a good idea to create issue(s) to document them so that you could tackle them later. I am personally not aware of other issues.

>  I fixed a few basic ones

Could you please link to the commit(s)?

>  I anyway has another task for code cleanup after the sample applications

Ok

> I will push the few fixes that are fine and keep the dependencies one disabled for now till I start working on code clean up ticket?

Sounds good. Would be nice to push some fixes.

**Comment by salonijain0918** [comment]
With upgradation to pylint to 2.11, new pep8 checks are raised with newer version, I fixed approximately all the ones that are being reported here though I can see more in my local setup. Have just disabled the check for circular imports, will try fixing it with a clear head.

**Review by kyrylo — APPROVED** [review]

**Pull request merged**
